config/routes.rb
Rails.application.routes.draw do
  concern :oai_provider, BlacklightOaiProvider::Routes.new

  mount Bulkrax::Engine, at: '/'
  post 'greetings/hello(.:format)'
  post 'greetings/hello_csv(.:format)'
  mount RailsAdmin::Engine => '/site_admin', as: 'rails_admin'
  mount Riiif::Engine => 'images', as: :riiif if Hyrax.config.iiif_image_server?
        mount BrowseEverything::Engine => '/browse'

  mount Zizia::Engine => '/'
  post '/csv_imports/be_upload(.:format)', to: 'zizia/csv_imports#be_upload'

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :oai_provider

    concerns :searchable
  end

  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'

  mount Qa::Engine => '/authorities'
  mount Hyrax::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'hyrax/homepage#index'
  curation_concerns_basic_routes
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get 'importer_documentation/shared_folder', to: 'zizia/importer_documentation#shared_folder'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/zizia/csv_import.rb
require_dependency Zizia::Engine.config.root.join('app', 'models', 'zizia', 'csv_import.rb').to_s

class Zizia::CsvImport

	delegate :selected_files, to: :manifest, prefix: true

	delegate :selected_files=, to: :manifest, prefix: true

	delegate :validate, to: :manifest, prefix: true

end

app/controllers/zizia/csv_imports_controller.rb
require_dependency Zizia::Engine.config.root.join('app', 'controllers', 'zizia', 'csv_imports_controller.rb').to_s

# The be_upload, cloud_files and other methods are borrowed from Bulkrax which uses the 'browseEverything' gem.

class Zizia::CsvImportsController

	def be_upload
		respond_to do |format|
			# format.html { render html: "GREETINGS EARTHLINGS! (Chill!  Just having some fun!)" }
			format.json { render json: ( be_upload_doit params[ :cloud_files ] ) }
			# format.js   { render :layout => false }
		end
	end

	def be_upload_doit ( cloud_files )
		if ( !cloud_files.nil? )
			myFiles = JSON.parse (cloud_files)
			retrieve_cloud_files(myFiles)
			ret = { "result" => true }
		else
			ret = { "result" => false }
		end
	end

	# The tmp directory path for browse_everything/cloud file uploads.
	def path_for_import
		path = Zizia.config.import_path
		FileUtils.mkdir_p(path) unless File.exist?(path)
		path
	end

	def load_and_authorize_preview
		@csv_import = ::Zizia::CsvImport.new(create_params)
		@csv_import.manifest_selected_files = cloud_params
		@csv_import.manifest_validate
		authorize! :create, @csv_import
	end

  private

		def create_params
			params.fetch(:csv_import, {}).permit(:manifest, :fedora_collection_id, :update_actor_stack)
		end

		def cloud_params
			params.permit(selected_files: {}).fetch(:selected_files).to_h if params&.[](:selected_files)
		end

		def files_for_import(cloud_files)
			return if cloud_files.blank?

			if cloud_files.present?
				# For BagIt, there will only be one bag, so we get the file_path back and set import_file_path
				# For CSV, we expect only file uploads, so we won't get the file_path back
				# and we expect the import_file_path to be set already
				target = @importer.parser.retrieve_cloud_files(cloud_files)
				@importer[:parser_fields]['import_file_path'] = target unless target.blank?
			end
			@importer.save
		end

		def retrieve_cloud_files(files)
		  return if files.blank?

		  files_path = path_for_import
		  FileUtils.mkdir_p(files_path) unless File.exist?(files_path)

		  files.each_pair do |_key, file|
				# fixes bug where auth headers do not get attached properly
				if file['auth_header'].present?
					file['headers'] ||= {}
					file['headers'].merge!(file['auth_header'])
				end
			  # this only works for uniquely named files
			  target_file = File.join(files_path, file['file_name'].tr(' ', '_'))
			  Zizia::DownloadCloudFileJob.perform_later(file, target_file)
		  end

		  return nil
		end

end

app/controllers/zizia/importer_documentation_controller.rb
require_dependency Zizia::Engine.config.root.join('app', 'controllers', 'zizia', 'importer_documentation_controller.rb').to_s

class Zizia::ImporterDocumentationController
  def shared_folder
  end
end

app/views/zizia/csv_imports/_browse_everything.html.erb
<div id='cloud-files'>
	<button type="button" data-toggle="browse-everything" data-route="<%=browse_everything_engine.root_path%>"
		data-target="#zizia-csv-imports-new" class="btn btn-primary" id="browse">
		<span class="glyphicon glyphicon-plus"></span>
		Add Cloud Files
	</button>
</div>

app/views/zizia/csv_imports/_collection_selection.html.erb
<%= form.select :fedora_collection_id, options_for_select(collections_for_select.sort()), {}, class: "form-control", id: "fedora_collection_id", include_blank: true, required: true %>

app/views/zizia/csv_imports/_file_upload.html.erb
<%= form.file_field :manifest, required: true, id: 'file-upload', class: "file-upload form-control", onchange: "Zizia.displayUploadedFile()", accept: "text/csv" %>
<label for="file-upload" class="btn btn-lg btn-default"><span class="glyphicon glyphicon-upload"></span> Upload Your CSV</label>
<div id="file-upload-display"></div>

app/views/zizia/csv_imports/_form.html.erb
<%= form_with(model: csv_import, local: true, html: { multipart: true, id: "zizia-csv-imports-new" }, url: preview_csv_import_path) do |form| %>
  <script>var IMPORT_PATH = "<%= ENV['IMPORT_PATH'] %>" </script>

  <div id="results"></div>

  <%= form.hidden_field :manifest_cache %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <h3><span class="bullet">1</span> Prepare Your Content</h3>
          <div class="well well-sm">
            <h4><span class="bullet" style="margin-top: 5px;">A</span></h4>

            <h4>Read the Metadata Field Guide:</h4>
            <p>The Metadata Field Guide details what fields are available for import and what their values should be.</p>
            <div class="text-center">
              <a href="/importer_documentation/guide" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-book"></i> Field Guide</a>
            </div>
          </div>
          <% if collections? %>
            <div class="well well-sm">
              <h4><span class="bullet" style="margin-top: 5px;">B</span></h4>

              <h4>Upload a CSV:</h4>
              <p>The CSV lists the collection metadata and files you want to import.</p>
              <div class="text-center">
                <%= render "file_upload", form: form  %>
              </div>
            </div>
          <% end %>

					<% if Hyrax.config.browse_everything? %>
						<div class="well well-sm">
							<h4><span class="bullet" style="margin-top: 5px;">C</span></h4>

						<h4>Choose Files to Import:</h4>
						<p>Select files to upload from the file system. These must match with the 'files' column in your CSV. All filenames must be unique.</p>
						<div class="text-center">
							<%= render 'browse_everything', form: form %>
						</div>
					</div>
					<% end %>

        </div>

        <div class="col-md-4">
          <h3><span class="bullet">2a</span> Choose Your Settings</h3>
          <% if collections? %>
            <div class="well well-sm">
              <h4><span class="bullet" style="margin-top: 5px;">A</span></h4>

              <h4>Choose a Collection:</h4>
              <p>Choose the collection where you'd like your new works to be imported.</p>
              <div class="text-center">
                <%= render "collection_selection", form: form %>
              </div>
            </div>
            <div class="well well-sm">
            <!-- <div id="csv-content" style="display:none;"></div> -->
              <h4><span class="bullet" style="margin-top: 5px;">B</span></h4>

              <h4>Select Update Behavior:</h4>
              <p>New works will always be added to the repository. Existing works can be overwritten, updated,
                or ignored.</p>
              <div class="text-center">
                <%= render "update_actor_stack", form: form %>
              </div>
            </div>
            <h3  style="margin-bottom: .75em;"><span class="bullet">2b</span> Preview/Start Your Import</h3>
            <div class="well well-sm">
              <h4><span class="bullet" style="margin-top: 5px;">A</span></h4>

              <h4>Preview Your Import:</h4>
              <p>The CSV file will be scanned for errors.  If it looks ok, you will be able to start the import.</p>
              <div class="text-center">
                <%= render "actions", form: form %>
              </div>
            </div>
          <% else %>
            <div class="well well-sm no-collection ">
              <h4><span class="bullet">A</span></h4>
              <div class="step">
                You must <a href="/dashboard/collections">create a collection</a> before importing content.
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-4">
          <h3><span class="bullet">3</span> Monitor Your Progress</h3>
            <div class="well well-sm">
            <h4><span class="bullet" style="margin-top: 5px;">A</span></h4>

            <h4>Sidekiq Job Status</h4>
            <p>Sidekiq checks the status of all jobs that have been submitted for import.</p>
            <div class="text-center">
              <a href="/sidekiq/busy" target="_blank" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-list"></i>&nbsp;Sidekiq Jobs</a>
            </div>
          </div>
          <div class="well well-sm">
            <h4><span class="bullet" style="margin-top: 5px;">B</span></h4>

            <h4>Check History</h4>
            <p>Checks the history of all batches that have been submitted for import.</p>
            <div class="text-center">
              <a href="/csv_import_details/index" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-list"></i> Import History</a>
            </div>
          </div>
        </div>
      </div> <!-- row -->
      <div class="row">
        <%= render "error", csv_import: csv_import %>
      </div>  <!-- row -->
    </div> <!-- panel-body -->
  </div> <!-- panel -->
<% end %>

app/views/zizia/csv_imports/_update_actor_stack.html.erb
<%= form.select :update_actor_stack, options_for_select([['Overwrite All Files & Metadata', 'HyraxDelete'],
                                                         ['Update Existing Metadata, create new works', 'HyraxMetadataOnly'],
                                                         ['Ignore Existing Works, new works only', 'HyraxOnlyNew' ]]), {}, class: "form-control", id: "update_actor_stack_id", include_blank: true, required: true  %>

app/views/zizia/csv_imports/preview.html.erb
<h2><span class="glyphicon glyphicon-cloud-upload"></span> Preview your CSV Import</h2>
<div class="panel panel-default">
  <div class="panel-body">
    <div id='csv_info'>
      <% if @csv_import.manifest.file %>
        <div class="row">
          <div class="col-md-4">
            <label> CSV Manifest: </label>
            <%= File.basename(@csv_import.manifest.to_s) %>
          </div>
          <div class="col-md-4">
            <label> Collection: </label>
            <%= ActiveFedora::SolrService.query("id:#{@csv_import.fedora_collection_id}")[0]['title_tesim'][0] %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <label> IMPORT_PATH: </label>
            <%= (File.directory?(ENV['IMPORT_PATH']) ? ENV['IMPORT_PATH'] : 'NO IMPORT DIRECTORY') %>
          </div>
        </div>
      <% end %>

      <%= render 'record_count', locals: { csv_import: @csv_import } %>

      <% unless File.directory?(ENV['IMPORT_PATH']) %>
        <div class="row">
          <div class="col-md-8">
            <div class="alert alert-danger">
              <div id='csv_errors'>
                <b><i class="glyphicon glyphicon-remove-sign"></i> This import has the following errors:</b>
                <ul>
                    <li>The import directory does not exist.  Have your system administrator set it up. (Looking for: <%= ENV['IMPORT_PATH'] %>)</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <% unless @csv_import.manifest_errors.empty? %>
        <div class="row">
          <div class="col-md-8">
            <div class="alert alert-danger">
              <div id='csv_errors'>
                <b><i class="glyphicon glyphicon-remove-sign"></i> The CSV file has the following errors:</b>
                <ul>
                  <% @csv_import.manifest_errors.each do |error| %>
                    <li> <%= error %> </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <% unless @csv_import.manifest_warnings.empty? %>
        <div class="row">
          <div class="col-md-6">
            <div class="alert alert-warning">
              <div id='csv_warnings'>
                <b><i class="glyphicon glyphicon-exclamation-sign"></i> The CSV file has the following warnings:</b>
                <ul>
                  <% @csv_import.manifest_warnings.each do |warning| %>
                    <li> <%= warning %> </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <% if ( @csv_import.manifest_errors.empty? && File.directory?(ENV['IMPORT_PATH']) )%>
        <div class="row">
          <div class="col-md-2">
            <%= render 'start_import_form', csv_import: @csv_import, class: "btn btn-large btn-danger" %>
          </div>
          <div class="col-md-2">
            <%= link_to 'Cancel', new_csv_import_path, class: "btn btn-lg btn-danger" %>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col-md-4">
            <div class="well"><p>You will need to correct the errors with the CSV file before you can continue.</p></br>
              <div class="text-center"><%= link_to 'Try Again', new_csv_import_path, class: 'btn btn-lg btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>